# Generated by Django 5.0.6 on 2024-09-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
